FROM blockcollider/bcnode

RUN apt-get update && apt-get install -y --no-install-recommends libfile-slurp-perl patch && rm -rf /var/lib/apt/lists/*

ARG BC_NODE_IMAGE_ID
# DONT change the label key: bc.node.docker_image_id
LABEL bc.node.docker_image_id=${BC_NODE_IMAGE_ID}

# Custom entrypoint
COPY bcnode/docker-entrypoint.sh /

COPY bcnode/monkey-patch /tmp

COPY bcnode/officer.js.patch /tmp

RUN patch ./lib/mining/officer.js /tmp/officer.js.patch

ENTRYPOINT [ "/docker-entrypoint.sh" ]
